name: 构建docker镜像
env:
  my_dockerfile: Dockerfile
# 手动触发
on: workflow_dispatch

jobs:
  build:
    # 当前脚本是在容器中运行的，对应的镜像是ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      run: 
        docker rmi $(docker images -q)
    # 检出代码
    - uses: actions/checkout@v2        
    - name: Dump GitHub context
      run: 
        cd ${{ github.workspace }} && ls
    - name: Login docker hub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      # 指定login命令登录hub.docker.com，帐号和密码已经在GitHub网页中配置好了
      run: 
        docker login   --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD} registry.cn-shanghai.aliyuncs.com
        #docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - name: Build dockerfile
      run: 
        docker build --output "type=image,push=true"  -f ${my_dockerfile} -t  registry.cn-shanghai.aliyuncs.com/chinaamc/vllm:0.7.3.cuda12.4 .
